const baseDatos = 
{
    canciones:
    [
        {
            id: "c1",
            nombre: "Animals",
            artista: "Martin Garrix",
            id_artista: "a21",
            link: "gCYcHz2k5x0",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion1/cancion.jpg",

        },
        {
            id: "c2",
            nombre: "Titanium",
            artista: "David Guetta ft. Sia",
            id_artista: "a9",
            link: "JRfuAukYTKg",
            genero: "Pop",
            id_genero: "g2",
            imagen: "../Statics/Media/canciones/cancion2/cancion.jpg",
        },
        {
            id: "c3",
            nombre: "Strobe",
            artista: "deadmau5",
            id_artista: "a32",
            link: "tKi9Z-f6qX4",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion3/cancion.jpg",
        },
        {
            id: "c4",
            nombre: "Bangarang",
            artista: "Skrillex ft. Sirah",
            id_artista: "a28",
            link: "YJVmu6yttiw",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion4/cancion.jpg",
        },
        {
            id: "c5",
            nombre: "Levels",
            artista: "Avicii",
            id_artista: "a2",
            link: "_ovdm2yX4MA",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion5/cancion.jpg",
        },
        {
            id: "c6",
            nombre: "Stay Forever",
            artista: "Whethan ft. STRFKR",
            id_artista: "a31",
            link: "RDqTzc6PXi-gY",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion6/cancion.jpg",
        },
        {
            id: "c7",
            nombre: "Opus",
            artista: "Eric Prydz",
            id_artista: "a11",
            link: "I9e3X3SEm1Y",
            genero: "Electronic",
            id_genero: "g1",
            imagen: "../Statics/Media/canciones/cancion7/cancion.jpg",
        },
        {
            id: "c8",
            nombre: "Midnight City",
            artista: "M83",
            id_artista: "a18",
            link: "dX3k_QDnzHE",
            genero: "Pop",
            id_genero: "g2",
            imagen: "../Statics/Media/canciones/cancion8/cancion.jpg",
        },
        {
            id: "c9",
            nombre: "Toulouse",
            artista: "Nicky Romero",
            id_artista: "a27",
            link: "KrVC5dm5fFc",
            genero: "Electronic",
            id_genero: "g1",
             imagen: "../Statics/Media/canciones/cancion9/cancion.jpg",
        },
        {
            id: "c10",
            nombre: "Get Lucky",
            artista: "Daft Punk ft. Pharrell Williams",
            id_artista: "a8",
            link: "5NV6Rdv1a3I",
            genero: "Pop",
            id_genero: "g2",
            imagen: "../Statics/Media/canciones/cancion10/cancion.jpg",
        },
        {
            id: "c11",
            nombre: "Hotel California",
            artista: "Eagles",
            id_artista: "a10",
            link: "AvP2pTOk8zU",
            genero: "Rock",
            id_genero: "g3",
            album: "Hotel California",
            imagen: "../Statics/Media/canciones/cancion11/cancion.jpg",
        },
        {
            id: "c12",
            nombre: "Memories",
            artista: "Maroon 5",
            id_artista: "a20",
            link: "o2DXt11SMNI",
            genero: "Pop",
            id_genero: "g2",
            album: "One Love",
            imagen: "../Statics/Media/canciones/cancion12/cancion.jpg",
        },
        {
            id: "c13",
            nombre: "My Way",
            artista: "Frank Sinatra",
            id_artista: "a12",
            link: "74vIWAR-fHY",
            genero: "Jazz",
            id_genero: "g4",
            album: "96 Months",
            imagen: "../Statics/Media/canciones/cancion13/cancion.jpg",
        },
        {
            id: "c14",
            nombre: "Flashback",
            artista: "Calvin Harris",
            id_artista: "a6",
            link: "crOJdLxl2AU",
            genero: "Electronic",
            id_genero: "g1",
            album: "Ready For The Weekend",
            imagen: "../Statics/Media/canciones/cancion14/cancion.jpg",            
        },
        {
            id: "c15",
            nombre: "While My Guitar Gently Weeps",
            artista: "The Beatles",
            id_artista: "a29",
            link: "VJDJs9dumZI",
            genero: "Rock",
            id_genero: "g3",
            album: "blanco",
            imagen: "../Statics/Media/canciones/cancion15/cancion.jpg",
        },
        {
            id: "c16",
            nombre: "Strawberry Fields Forever",
            artista: "The Beatles",
            id_artista: "a29",
            link: "HtUH9z_Oey8",
            genero: "Rock",
            id_genero: "g3",
            album: "Magical Mystery Tour",
            imagen: "../Statics/Media/canciones/cancion16/cancion.jpg",
        },
        {
            id: "c17",
            nombre: "Eleanor Rigby",
            artista: "The Beatles",
            id_artista: "a29",
            link: "HuS5NuXRb5Y",
            genero: "Pop",
            id_genero: "g2",
            album: "Revolver",
            imagen: "../Statics/Media/canciones/cancion17/cancion.jpg",
        },
        {
            id: "c18",
            nombre: "Boulevard of Broken Dreams",
            artista: "Green Day",
            id_artista: "a13",
            link: "Soa3gO7tL-c",
            genero: "Rock",
            id_genero: "g3",
            album: "American Idiot",
            imagen: "../Statics/Media/canciones/cancion18/cancion.jpg",
        },
        {
            id: "c19",
            nombre: "Riders on the Storm",
            artista: "The Doors",
            id_artista: "a30",
            link: "V4f0_aoFjTI",
            genero: "Rock",
            id_genero: "g3",
            album: "L.A.Woman",
            imagen: "../Statics/Media/canciones/cancion19/cancion.jpg",
        },
        {
            id: "c20",
            nombre: "One of These Nights",
            artista: "Eagles",
            id_artista: "a10",
            link: "NZebwtoOp3Q",
            genero: "Rock",
            id_genero: "g3",
            album: "One Of The Night",
            imagen: "../Statics/Media/canciones/cancion20/cancion.jpg",
        },
        {
            id: "c21",
            nombre: "Welcome Home (Sanitarium)",
            artista: "Metallica",
            id_artista: "a24",
            link: "_5vbUZmkhDk",
            genero: "Rock",
            id_genero: "g3",
            album: "Master of Puppets",
            imagen: "../Statics/Media/canciones/cancion21/cancion.jpg",
        },
        {
            id: "c22",
            nombre: "Sad But True",
            artista: "Metallica",
            id_artista: "a24",
            link: "8xPaeONSn_8",
            genero: "Rock",
            id_genero: "g3",
            album: "Metallica",
            imagen: "../Statics/Media/canciones/cancion22/cancion.jpg",
        },
        {
            id: "c23",
            nombre: "Creeping Death",
            artista: "Metallica",
            id_artista: "a24",
            link: "Q0GPD6FHnOU",
            genero: "Rock",
            id_genero: "g3",
            album: "Ride the Lightning",
            imagen: "../Statics/Media/canciones/cancion23/cancion.jpg",
        },
        {
            id: "c24",
            nombre: "Wonderwall",
            artista: "Bring Me The Horizon",
            id_artista: "a4",
            link: "CW8S8Rki5zE",
            genero: "Rock",
            id_genero: "g3",
            album: "Spotify Singles",
            imagen: "../Statics/Media/canciones/cancion24/cancion.jpg",
        },
        {
            id: "c25",
            nombre: "Take A Look Around",
            artista: "Limp Bizkit",
            id_artista: "a16",
            link: "53Hcbzj3Rmw",
            genero: "Rock",
            id_genero: "g3",
            album: "Chocolate Starfish and the Hot Dog Flavored Water",
            imagen: "../Statics/Media/canciones/cancion25/cancion.jpg",
        },
        {
            id: "c26",
            nombre: "Faith",
            artista: "Limp Bizkit",
            id_artista: "a16",
            link: "EQJMmjw8MVo",
            genero: "Rock",
            id_genero: "g3",
            album: "Three Dollar Bill, Y'all",
            imagen: "../Statics/Media/canciones/cancion26/cancion.jpg",
        },
        {
            id: "c27",
            nombre: "Tornado Of Souls",
            artista: "Megadeth",
            id_artista: "a23",
            link: "Nej8hldE25k",
            genero: "Rock",
            id_genero: "g3",
            album: "Rust in Peace",
            imagen: "../Statics/Media/canciones/cancion27/cancion.jpg",
        },
        {
            id: "c28",
            nombre: "Holy Wars... The Punishment Due",
            artista: "Megadeth",
            id_artista: "a23",
            link: "SLEvhW2g_ZE",
            genero: "Rock",
            id_genero: "g3",
            album: "Rust in Peace",
            imagen: "../Statics/Media/canciones/cancion28/cancion.jpg",
        },
        {
            id: "c29",
            nombre: "Kickstart My Heart",
            artista: "Mötley Crüe",
            id_artista: "a26",
            link: "sxlMSq_xq7o",
            genero: "Rock",
            id_genero: "g3",
            album: "Dr. Feelgood",
            imagen: "../Statics/Media/canciones/cancion29/cancion.jpg",
        },
        {
            id: "c30",
            nombre: "Trapped Under Ice",
            artista: "Metallica",
            id_artista: "a24",
            link: "0G3bv_bp9Wk",
            genero: "Rock",
            id_genero: "g3",
            album: "Ride the Lightning",
            imagen: "../Statics/Media/canciones/cancion30/cancion.jpg",
        },
        {
            id: "c31",
            nombre: "Concedimi",
            artista: "Matteo Romano",
            id_artista: "a22",
            link: "4Q5MCKZ31Io",
            genero: "Pop",
            id_genero: "g2",
            album: "Concedimi",
            imagen: "../Statics/Media/canciones/cancion31/cancion.jpg",
        },
        {
            id: "c32",
            nombre: "Quedate",
            artista: "3am",
            id_artista: "a1",
            link: "L6bRE3JVMZQ",
            genero: "Pop",
            id_genero: "g2",
            album: "Lluvia: Rain City",
            imagen: "../Statics/Media/canciones/cancion32/cancion.jpg",
        },
        {
            id: "C33",
            nombre: "Una Rosa",
            artista: "3am",
            id_artista: "a1",
            link: "6nghc9zSMu4",
            genero: "Pop",
            id_genero: "g2",
            album: "Rain City",
            imagen: "../Statics/Media/canciones/cancion33/cancion.jpg",
        },
        {
            id: "c34",
            nombre: "Solo",
            artista: "Jennie",
            id_artista: "a14",
            link: "cEZA3s8PlZk",
            genero: "Pop",
            id_genero: "g2",
            album: "Ruby",
            imagen: "../Statics/Media/canciones/cancion34/cancion.jpg",

        },
        {
            id: "c35",
            nombre: "WHISTLE",
            artista: "BlackPink",
            id_artista: "a3",
            link: "dISNgvVpWlo",
            genero: "Pop",
            id_genero: "g2",
            album: "Square One",
            imagen: "../Statics/Media/canciones/cancion35/cancion.jpg",
        },
        {
            id: "c36",
            nombre: "Tu me encantas",
            artista: "3am",
            id_artista: "a1",
            link: "A-yxW8ALa-A",
            genero: "Pop",
            id_genero: "g2",
            album: "Rain City",
            imagen: "../Statics/Media/canciones/cancion36/cancion.jpg",
        },
        {
            id: "c37",
            nombre: "Love to hate me",
            artista: "BlackPink",
            id_artista: "a3",
            link: "S5Izt5EgAq0",
            genero: "Pop",
            id_genero: "g2",
            album: "The Album",
            imagen: "../Statics/Media/canciones/cancion37/cancion.jpg",
        },
        {
            id: "c38",
            nombre: "Antes de irme",
            artista: "Ludiko-Sidu Martines",
            id_artista: "a17",
            link: "Gx5ai3HtShg",
            genero: "Hip-hop",
            id_genero: "g5",
            album: "SISTAHOOD",
            imagen: "../Statics/Media/canciones/cancion38/cancion.jpg",
        },
        {
            id: "c39",
            nombre: "Por la noche",
            artista: "Mala Rodríguez",
            id_artista: "a19",
            link: "nawuHf66fKQ",
            genero: "Hip-hop",
            id_genero: "g5",
            album: "Malamarismo",
            imagen: "../Statics/Media/canciones/cancion39/cancion.jpg",
        },
        {
            id: "c40",
            nombre: "ni me debes, ni te debo",
            artista: "Carin León - Camilo",
            id_artista: "a7",
            link: "a6Or1V7XUUo",
            genero: "Regional",
            id_genero: "g6",
            album: "Colmillo de leche",
            imagen: "../Statics/Media/canciones/cancion40/cancion.jpg",
        },
        {
            id: "c41",
            nombre: "Contacto",
            artista: "Camilo Séptimo",
            id_artista: "a5",
            link: "yjabuIzJgcI",
            genero: "Rock",
            id_genero: "g1",
            album: "Navegantes",
            imagen: "../Statics/Media/canciones/cancion41/cancion.jpg",
        },
        {
            id: "c42",
            nombre: "Open Door",
            artista: "Mike Shinoda",
            id_artista: "a25",
            link: "99vueJmTJt0",
            genero: "Rock",
            id_genero: "g3",
            album: "Dropped Frames, Vol. 1",
            imagen: "../Statics/Media/canciones/cancion42/cancion.jpg",
        },
        {
            id: "c43",
            nombre: "Prove You Wrong",
            artista: "Mike Shinoda",
            id_artista: "a25",
            link: "PxLjXGGx49c",
            genero: "Rock",
            id_genero: "g3",
            album: "Post Traumatic",
            imagen: "../Statics/Media/canciones/cancion43/cancion.jpg",
        },
        {
            id: "c44",
            nombre: "No te reconozco",
            artista: "Camilo Séptimo",
            id_artista: "a5",
            link: "0oJmWfZFoIw",
            genero: "Rock",
            id_genero: "g3",
            album: "ECOS",
            imagen: "../Statics/Media/canciones/cancion44/cancion.jpg",
        },
        {
            id: "c45",
            nombre: "The Emptiness Machine",
            artista: "Linkin Park",
            id_artista: "a15",
            link: "GShxN7ONPmI",
            genero: "Rock",
            id_genero: "g3",
            album: "From Zero",
            imagen: "../Statics/Media/canciones/cancion45/cancion.jpg",
        },
        {
            id: "c46",
            nombre: "Sit Next to Me",
            artista: "Foster the people",
            id_artista: "a33",
            link: "5AGsQ4-V4h8",
            genero: "Pop", 
            id_genero: "g2",
            album: "Sacred Hearts Club",
            imagen: "../Statics/Media/canciones/cancion46/cancion.jpg", 
        },
        {
            id: "c47",
            nombre: "Call It What You Want",
            artista: "Foster the people",
            id_artista: "a33",
            link: "-WuaAvF4oEA",
            genero: "Pop",
            id_genero: "g2",
            album: "Torches",
            imagen: "../Statics/Media/canciones/cancion47/cancion.jpg",
        },
        {
            id: "c48",
            nombre: "The Darkness That You Fear",
            artista: "The Chemical Brothers",
            id_artista: "a35",
            link: "FtqG6UZhWoA",
            genero: "Electronic",
            id_genero: "g1",
            album: "The Darkness That You Fear - Single",
            imagen: "../Statics/Media/canciones/cancion48/cancion.jpg",

        },
        {
            id: "c49",
            nombre: "Vandalize",
            artista: "ONE OK ROCK",
            id_artista: "a34",
            link: "1gRfBLSqyNE",
            genero: "Rock",
            id_genero: "g3",
            album: "Luxury Desease",
            imagen: "../Statics/Media/canciones/cancion49/cancion.jpg",
        },
        {
            id: "c50",
            nombre: "Broken Heart of Gold",
            artista: "ONE OK ROCK",
            id_artista: "a34",
            link: "hDy9BrB9_VU",
            genero: "Rock",
            id_genero: "g3",
            album: "Broken Heart of Gold - Single",
            imagen: "../Statics/Media/canciones/cancion50/cancion.jpg",
        }
    ],
    generos:
    [
        {
            id: "g1",
            nombre: "Electronic",
            descripcion: "Música basada principalmente en sonidos sintetizados y producción digital; incluye subgéneros como house, dubstep y techno."
        },
        {
            id: "g2",
            nombre: "Pop",
            descripcion: "Género popular con melodías accesibles, estructuras simples y gran presencia vocal; engloba estilos como synthpop, dance pop y baladas."
        },
        {
            id: "g3",
            nombre: "Rock",
            descripcion: "Género enfocado en guitarras eléctricas, bajo, batería y energía cruda; abarca subgéneros como alternativo, metal y psicodélico."
        },
        {
            id: "g4",
            nombre: "Jazz",
            descripcion: "Género musical con improvisación, armonías sofisticadas y raíces afroamericanas; frecuentemente incluye instrumentos de viento y piano."
        },
        {
            id: "g5",
            nombre: "Hip-hop",
            descripcion: "Estilo basado en rimas rítmicas (rap), beats marcados y cultura urbana; puede fusionarse con funk, soul o trap."
        },
        {
            id: "g6",
            nombre: "Regional",
            descripcion: "Música tradicional o folklórica representativa de una región; en este caso, corridos mexicanos con letras narrativas."
        }
    ],
    artistas:
    [
        {
            id: "a1",
            artista: "3am",
            imagen: "../Statics/Media/canciones/cancion33/artista.jpg",
            descripcion: "Dúo musical hispanohablante conocido por su estilo melódico y letras sensibles dentro del pop alternativo."
        },
        {
            id: "a2",
            artista: "Avicii",
            imagen: "../Statics/Media/canciones/cancion5/artista.jpg",
            descripcion: "DJ y productor sueco que revolucionó la música electrónica con melodías emotivas y colaboraciones icónicas."
        },
        {
            id: "a3",
            artista: "BlackPink",
            imagen: "../Statics/Media/canciones/cancion35/artista.jpg",
            descripcion: "Grupo femenino de K-pop surcoreano que combina pop, rap y EDM con coreografías potentes y presencia global."
        },
        {
            id: "a4",
            artista: "Bring Me The Horizon",
            imagen: "../Statics/Media/canciones/cancion24/artista.jpg",
            descripcion: "Banda británica que evolucionó del metalcore al rock alternativo y experimental con gran éxito internacional."
        },
        {
            id: "a5",
            artista: "Camilo Séptimo",
            imagen: "../Statics/Media/canciones/cancion41/artista.jpg",
            descripcion: "Banda mexicana de rock alternativo con letras introspectivas y un estilo atmosférico y moderno."
        },
        {
            id: "a6",
            artista: "Calvin Harris",
            imagen: "../Statics/Media/canciones/cancion14/artista.jpg",
            descripcion: "Productor y DJ escocés que domina las listas globales con hits de dance pop y colaboraciones con grandes artistas."
        },
        {
            id: "a7",
            artista: "Carin León - Camilo",
            imagen: "../Statics/Media/canciones/cancion40/artista.jpg",
            descripcion: "Fusión entre el regional mexicano de Carin León y el pop fresco del colombiano Camilo, una colaboración de estilos únicos."
        },
        {
            id: "a8",
            artista: "Daft Punk ft. Pharrell Williams",
            imagen: "../Statics/Media/canciones/cancion10/artista.jpg",
            descripcion: "Iconos del electro francés junto con el estilo funky de Pharrell; su unión marcó un antes y después en la música disco moderna."
        },
        {
            id: "a9",
            artista: "David Guetta ft. Sia",
            imagen: "../Statics/Media/canciones/cancion2/artista.jpg",
            descripcion: "Dúo imbatible en la electrónica y el pop; Guetta y Sia lograron una fórmula explosiva de emoción y energía."
        },
        {
            id: "a10",
            artista: "Eagles",
            imagen: "../Statics/Media/canciones/cancion11/artista.jpg",
            descripcion: "Legendaria banda estadounidense de rock y country rock, famosa por sus armonías vocales y clásicos como 'Hotel California'."
        },
        {
            id: "a11",
            artista: "Eric Prydz",
            imagen: "../Statics/Media/canciones/cancion7/artista.jpg",
            descripcion: "Productor sueco de música electrónica conocido por su enfoque progresivo y su icónico track 'Opus'."
        },
        {
            id: "a12",
            artista: "Frank Sinatra",
            imagen: "../Statics/Media/canciones/cancion13/artista.jpg",
            descripcion: "Voz legendaria del pop clásico y el jazz, símbolo de la elegancia vocal del siglo XX."
        },
        {
            id: "a13",
            artista: "Green Day",
            imagen: "../Statics/Media/canciones/cancion18/artista.jpg",
            descripcion: "Banda estadounidense de punk rock con letras cargadas de rebeldía y un sonido explosivo y melódico."
        },
        {
            id: "a14",
            artista: "Jennie",
            imagen: "../Statics/Media/canciones/cancion34/artista.jpg",
            descripcion: "Miembro de BlackPink y solista, Jennie mezcla pop coreano con influencias de hip-hop y estilo elegante."
        },
        {
            id: "a15",
            artista: "Linkin Park",
            imagen: "../Statics/Media/canciones/cancion45/artista.jpg",
            descripcion: "Banda estadounidense pionera en combinar rock alternativo, nu metal y rap con un enfoque emocional y potente."
        },
        {
            id: "a16",
            artista: "Limp Bizkit",
            imagen: "../Statics/Media/canciones/cancion25/artista.jpg",
            descripcion: "Grupo conocido por su mezcla de rock, rap y actitud rebelde, íconos del nu metal de los años 2000."
        },
        {
            id: "a17",
            artista: "Ludiko-Sidu Martines",
            imagen: "../Statics/Media/canciones/cancion38/artista.jpg",
            descripcion: "Dúo de rap comprometido con letras sociales, identidades afro-latinas y empoderamiento femenino."
        },
        {
            id: "a18",
            artista: "M83",
            imagen: "../Statics/Media/canciones/cancion8/artista.jpg",
            descripcion: "Proyecto de synthpop y rock alternativo con un estilo cinematográfico y nostálgico."
        },
        {
            id: "a19",
            artista: "Mala Rodríguez",
            imagen: "../Statics/Media/canciones/cancion39/artista.jpg",
            descripcion: "Rapper española pionera del hip-hop en español, mezcla fuerza lírica con identidad cultural intensa."
        },
        {
            id: "a20",
            artista: "Maroon 5",
            imagen: "../Statics/Media/canciones/cancion12/artista.jpg",
            descripcion: "Banda pop rock estadounidense con un sonido fresco, pegajoso y dominado por la voz de Adam Levine."
        },
        {
            id: "a21",
            artista: "Martin Garrix",
            imagen: "../Statics/Media/canciones/cancion1/artista.jpg",
            descripcion: "Joven DJ y productor neerlandés que conquistó la electrónica mundial con su hit 'Animals'."
        },
        {
            id: "a22",
            artista: "Matteo Romano",
            imagen: "../Statics/Media/canciones/cancion31/artista.jpg",
            descripcion: "Cantautor italiano de baladas pop suaves, conocido por su sensibilidad vocal y letras introspectivas."
        },
        {
            id: "a23",
            artista: "Megadeth",
            imagen: "../Statics/Media/canciones/cancion28/artista.jpg",
            descripcion: "Banda icónica de thrash metal, formada por el exguitarrista de Metallica, famosa por su virtuosismo técnico."
        },
        {
            id: "a24",
            artista: "Metallica",
            imagen: "../Statics/Media/canciones/cancion23/artista.jpg",
            descripcion: "Una de las bandas de metal más influyentes del mundo, responsables de himnos como 'Master of Puppets'."
        },
        {
            id: "a25",
            artista: "Mike Shinoda",
            imagen: "../Statics/Media/canciones/cancion42/artista.jpg",
            descripcion: "Músico, rapero y productor, cofundador de Linkin Park y solista con sonidos alternativos y personales."
        },
        {
            id: "a26",
            artista: "Mötley Crüe",
            imagen: "../Statics/Media/canciones/cancion29/artista.jpg",
            descripcion: "Banda estadounidense de glam metal conocida por su actitud irreverente, exceso y éxitos ochenteros."
        },
        {
            id: "a27",
            artista: "Nicky Romero",
            imagen: "../Statics/Media/canciones/cancion9/artista.jpg",
            descripcion: "DJ y productor holandés reconocido en la escena EDM por sus sonidos enérgicos y colaboraciones masivas."
        },
        {
            id: "a28",
            artista: "Skrillex ft. Sirah",
            imagen: "../Statics/Media/canciones/cancion4/artista.jpg",
            descripcion: "Explosiva combinación de dubstep agresivo y versos rítmicos, con Skrillex a la producción y Sirah rapeando."
        },
        {
            id: "a29",
            artista: "The Beatles",
            imagen: "../Statics/Media/canciones/cancion15/artista.jpg",
            descripcion: "Cuarteto británico que revolucionó la música moderna con su evolución del pop al rock psicodélico."
        },
        {
            id: "a30",
            artista: "The Doors",
            imagen: "../Statics/Media/canciones/cancion19/artista.jpg",
            descripcion: "Banda estadounidense de rock psicodélico liderada por la intensa voz y poesía de Jim Morrison."
        },
        {
            id: "a31",
            artista: "Whethan ft. STRFKR",
             imagen: "../Statics/Media/canciones/cancion6/artista.jpg",
            descripcion: "Colaboración indie-electrónica que fusiona sintetizadores brillantes y vocales nostálgicas."
        },
        {
            id: "a32",
            artista: "deadmau5",
            imagen: "../Statics/Media/canciones/cancion3/artista.jpg",
            descripcion: "Referente canadiense del progressive house y la música electrónica de club, famoso por su máscara de ratón."
        },
        {
            id: "a33",
            artista: "Foster The People",
            imagen: "../Statics/Media/canciones/cancion46/artista.jpg",
            descripcion: "Indie pop bailable, letras introspectivas y ritmos pegajosos."
        },
        {
            id: "a34",
            artista: "ONE OK ROCK",
            imagen: "..//Statics/Media/canciones/cancion49/artista.jpg",
            descripcion: "Rock japonés emotivo, enérgico y con influencia occidental."
        },
        {
            id: "a35",
            artista: "The Chemical Brothers",
            imagen: "../Statics/Media/canciones/cancion48/artista.jpg",
            descripcion: "Electrónica psicodélica, potente, con bases rítmicas experimentales."
        }
    ]
}
